### PR TITLE
Add build action

### PR DESCRIPTION
**Pull request by dreua**

### CODE REVIEW

**Comment by mrbesen** [comment]
I have not worked with github actions yet, but maybe we can add an action to build the debian package with  `debuild --no-sign` or a similar command. debuild also runs make.

**Comment by cnlohr** [comment]
Just let me know if there's anything I need to do.

**Comment by dreua** [comment]
@mrbesen Yes, I'm planning to do that. Can you give me the full command you are using to build locally? It would be built on Ubuntu, however, that may or may not be compatible with Debian. We can use custom Docker images to build for different versions or Debian specifically, I've done the same for Fedora/RPM Builds of PDF Arranger.

**Comment by mrbesen** [comment]
```bash
# asuming all dependencyes are installed
$ git clone --recurse-submodules https://github.com/mrbesen/cnping -b icon
[...]
$ cd cnping/
$ debuild --no-sign
[...]
$ cd ..
$ ls
cnping                    cnping_1.0.0_amd64.buildinfo  cnping_1.0.0_amd64.deb  cnping_1.0.0.tar.xz
cnping_1.0.0_amd64.build  cnping_1.0.0_amd64.changes    cnping_1.0.0.dsc        cnping-dbgsym_1.0.0_amd64.ddeb
```
Its actually that simple

**Pull request merged**
