### PR TITLE
Update makefile

### PR DESCRIPTION
**Pull request by Teslaspecter**
Updated the makefile for compatibility with WSL. I had severe troubles making it until I added the recursive options to the makefile commands. 

I'm very new to Github, and I only started messing with WSL last week so ignore my changes if they dont make sense.

In regards to my last note, cnping on wsl is still unstable on my system; I am probably not doing something correctly on making it.
The compiled cnping exe does work perfectly and has been very helpful

### CODE REVIEW

**Comment by cnlohr** [comment]
You really shouldn't need those flags on the Makefile, I don't think.  What errors do you get when you compile it normally?

**Comment by Teslaspecter** [comment]
> You really shouldn't need those flags on the Makefile, I don't think. What errors do you get when you compile it normally?

I don't remember at the moment, I'll be able to replicate the issue later tonight after work! It probably had something to do with not putting it in the default directory in my linux environment. Will get back on this tonight

**Comment by cnlohr** [comment]
let me know

**Comment by cnlohr** [comment]
I am closing this PR for now.

**Pull request closed without merging**
