### PR TITLE
Add basic RDUI stuff

### PR DESCRIPTION
**Pull request by overlisted**
I added RDUI as a submodule and used it to make a graphical menu where you enter the hostname (in a not very elegant way tho).

### CODE REVIEW

**Comment by overlisted** [comment]
I will polish RDUI and so have to change how it's used. Please don't accept this PR yet

**Comment by overlisted** [comment]
I guess, that's all what I needed to do change in the RDUI headers.

**Comment by dreua** [comment]
I just tried this branch and it's a cool demo for sure! RDUI (= RawDraw User Interface) is a very basic low level way of user input, if that stuff continues to grow we end up competing with Qt :stuck_out_tongue_winking_eye: 

For usage on PC it's only a nerdy gimmick imo but I like the idea that we could reuse the same code on other platforms like Android or embedded systems.

I don't know what @cnlohr thinks about this addition, especially since it adds an external dependency. (Are there plans to integrate RDUI into rawdraw?)

The following points are blockers for me:
- [ ] If cloned with `--recursive` you end up with multiple duplicates of submodules.
- [ ] I can't enter special characters like `:` and `/`, these are important if you want to use the Http ping feature. (I have a qwertz keyboard layout but pressing the buttons like it was qwerty doesn't help.)
- [ ] Colors are off. I'd suggest rebasing on master, it has the current rawdraw with correct colors.

More stuff I noticed / nice to have:
- [ ] When the window is resized, the mouse hit-boxes are off (unusable)
- [ ] Basic keyboard navigation would be cool (Tab / Shift+Tab / Enter) to switch fields, start pinging.
- [ ] Would it be hard to support copy & paste? :see_no_evil:

**Comment by overlisted** [comment]
- Going to fix
- They work for me both on Linux and Wine, maybe you've cloned an old version?
- That's fixed
- It's a problem with rawdraw
- There's `Ctrl + Enter` and I'm kinda lazy to implement `Tab`
- Yes

**Comment by overlisted** [comment]
Also, there _are_ plans to integrate it into rawdraw. You should join cnlohr's Discord, we discuss everything there

**Comment by dreua** [comment]
I've cloned the version in this pull request yesterday, which one should I clone?

And yes, the duplicate submodules are a problem, because it wastes everyone's time when they need to figure out which files/submodules are relevant and which are merely copies lying around for no reason.

**Pull request closed without merging**
